#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "ntp"

cookbook 'nginx',
  :git => 'https://github.com/opscode-cookbooks/nginx.git'

cookbook 'postgresql',
  :git => 'https://github.com/phlipper/chef-postgresql'
  
cookbook 'redis',
  :git => 'https://github.com/ctrabold/chef-redis'

cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv'

cookbook 'ruby_build'

cookbook 'main',
  :path => 'vendor/cookbooks/main'


